Repository cqframework/clinical-reasoning, pull requests merged in 2024-02, with the labels that each got.

#413 Fixes for malformed codes and valuesets
  .vscode/settings.json
  cqf-fhir-cql/src/main/java/org/opencds/cqf/fhir/cql/engine/terminology/RepositoryTerminologyProvider.java
  cqf-fhir-cql/src/test/java/org/opencds/cqf/fhir/cql/engine/terminology/RepositoryTerminologyProviderTest.java
  cqf-fhir-cql/src/test/resources/org/opencds/cqf/fhir/cql/engine/terminology/MissingCodeValueSet.json
  cqf-fhir-cql/src/test/resources/org/opencds/cqf/fhir/cql/engine/terminology/MissingSystemValueSet.json
  cqf-fhir-cql/src/test/resources/org/opencds/cqf/fhir/cql/engine/terminology/ValidValueSet.json
Labels: bug

#426 Add Windows build to PR check to catch platform-specific issues
  .github/workflows/build.yml
  .github/workflows/check-pr.yaml
  .github/workflows/spotless.yml
  cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/activitydefinition/ActivityDefinitionProcessorTests.java
  cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/measure/r4/R4RepositoryTest.java
  cqf-fhir-test/src/main/java/org/opencds/cqf/fhir/test/Resources.java
Labels: chore

#429 Fix non-unique request resource ids
  cqf-fhir-cr/src/main/java/org/opencds/cqf/fhir/cr/plandefinition/apply/ProcessDefinition.java
  cqf-fhir-cr/src/test/java/org/opencds/cqf/fhir/cr/plandefinition/PlanDefinitionProcessorTests.java
  cqf-fhir-cr/src/test/resources/org/opencds/cqf/fhir/cr/plandefinition/r4/resources/PlanDefinition-multi-action-activity.json
Labels: bug, CDS
